name: fiction

services:
  backend:
    build:
      context: ./backend
      target: development
    env_file:
      - ./env/backend.env
      - ./env/db.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  db:
    image: mysql:9.2
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
