apiVersion: v1
data:
  MYSQL_DATABASE: fiction
  MYSQL_HOST: db
  MYSQL_PASSWORD: express
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: express
  MYSQL_USER: fiction
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-db-env
  name: db-env
